permissions:
  contents: read
name: Publish @anyone-protocol/anyone-client to npm

on:
  # push:
  #   tags:
  #     - 'v*'
  workflow_dispatch:

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Nomad job to publish @anyone-protocol/anyone-client to npm
        env:
          NOMAD_CACERT: operations/admin-ui-ca.crt
          NOMAD_TOKEN: ${{ secrets.NOMAD_TOKEN_ANYONE_CLIENT_PUBLISH_NPM }}
          NOMAD_ADDR: ${{ secrets.NOMAD_ADDR }}
        run: |
          # Determine VERSION from git tag, stripping ref and "v" prefix
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          
          # Update job template with VERSION
          sed \
            -i 's/\[\[ .version \]\]/'${VERSION}'/g' \
            operations/publish-anyone-client-npm.hcl

          curl \
            -L https://releases.hashicorp.com/nomad/1.10.2/nomad_1.10.2_linux_amd64.zip \
            -o nomad.zip
          unzip nomad.zip

          ./nomad job run operations/publish-anyone-client-npm.hcl
